
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";

const configuredUrl = process.env.DATABASE_URL ?? "file:./prisma/dev.db";
const databaseUrl = configuredUrl.startsWith("file:./")
  ? `file:${path.resolve(process.cwd(), configuredUrl.slice(5))}`
  : configuredUrl;
process.env.DATABASE_URL = databaseUrl;

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
